void setup(){Serial.begin(9600);delay(10);pinMode(PIN0, INPUT);
pinMode(PIN1, INPUT);
pinMode(PIN2, INPUT);
pinMode(PIN3, INPUT);
pinMode(PIN4, INPUT);
pinMode(PIN5, INPUT);
pinMode(PIN6, INPUT);
pinMode(PIN7, INPUT);
pinMode(PIN8, INPUT);
pinMode(PIN9, INPUT);
pinMode(PIN10, INPUT);
pinMode(PIN11, INPUT);
pinMode(PIN12, INPUT);
pinMode(PIN13, INPUT);
pinMode(PIN14, INPUT);
pinMode(PIN15, INPUT);
pinMode(PIN16, INPUT);
pinMode(PIN17, INPUT);
pinMode(PIN18, INPUT);
pinMode(PIN19, INPUT);
pinMode(PIN20, INPUT);
pinMode(PIN21, INPUT);
pinMode(PIN22, INPUT);
pinMode(PIN23, INPUT);
pinMode(PIN24, INPUT);
pinMode(PIN25, INPUT);
pinMode(PIN26, INPUT);
pinMode(PIN27, INPUT);
pinMode(PIN28, INPUT);
pinMode(PIN29, INPUT);
pinMode(PIN30, INPUT);
pinMode(PIN31, INPUT);
pinMode(PIN32, INPUT);
pinMode(PIN33, INPUT);
pinMode(PIN34, INPUT);
pinMode(PIN35, INPUT);

auto x1while = 1;
}